//
//  Recibos_Data.swift
//  Reto
//
//  Created by Jimena Gallegos on 13/10/23.
//

import Foundation

var listaRecibos = getRecibos()

func getRecibos() -> Array<Recibos>{
    var lista: Array<Recibos> = [
        Recibos(BITACORA: 1, DONANTE_APELLIDOM: "Flores", DONANTE_APELLIDOP: "Cabrera", DONANTE_COL: "ALTA VISTA", DONANTE_CP: "64840", DONANTE_DIR: "Balcones 45", DONANTE_MUN: "Monterrey", DONANTE_NOMBRE: "Jaime", DONANTE_TELCASA: "78191010", DONANTE_TELMOV: "3311103398", ESTATUS: "Pendiente", IMPORTE: 200, REPARTIDOR_ID: 1),
        Recibos(BITACORA: 2, DONANTE_APELLIDOM: "Rongel", DONANTE_APELLIDOP: "Gallegos", DONANTE_COL: "CENTRO", DONANTE_CP: "34500", DONANTE_DIR: "Balcones 45", DONANTE_MUN: "Hermosillo", DONANTE_NOMBRE: "Jimena", DONANTE_TELCASA: "78191010", DONANTE_TELMOV: "6623076006", ESTATUS: "Pendiente", IMPORTE: 200, REPARTIDOR_ID: 1),
        Recibos(BITACORA: 3, DONANTE_APELLIDOM: "Blanco", DONANTE_APELLIDOP: "Rongel", DONANTE_COL: "CENTRO", DONANTE_CP: "34500", DONANTE_DIR: "Balcones 45", DONANTE_MUN: "Hermosillo", DONANTE_NOMBRE: "America", DONANTE_TELCASA: "78191010", DONANTE_TELMOV: "6621020248", ESTATUS: "No Cobrado", IMPORTE: 200, REPARTIDOR_ID: 1),
        Recibos(BITACORA: 4, DONANTE_APELLIDOM: "Naranjo", DONANTE_APELLIDOP: "Garza", DONANTE_COL: "CENTRO", DONANTE_CP: "34500", DONANTE_DIR: "Balcones 45", DONANTE_MUN: "Hermosillo", DONANTE_NOMBRE: "Luis", DONANTE_TELCASA: "78191010", DONANTE_TELMOV: "6621020248", ESTATUS: "Cobrado", IMPORTE: 300, REPARTIDOR_ID: 1),
        Recibos(BITACORA: 5, DONANTE_APELLIDOM: "Gamez", DONANTE_APELLIDOP: "Garcia", DONANTE_COL: "CENTRO", DONANTE_CP: "34500", DONANTE_DIR: "Balcones 45", DONANTE_MUN: "Hermosillo", DONANTE_NOMBRE: "Elisa", DONANTE_TELCASA: "78191010", DONANTE_TELMOV: "6621020248", ESTATUS: "Cobrado", IMPORTE: 200, REPARTIDOR_ID: 1),
        Recibos(BITACORA: 6, DONANTE_APELLIDOM: "Hortencia", DONANTE_APELLIDOP: "Ortiz", DONANTE_COL: "CENTRO", DONANTE_CP: "34500", DONANTE_DIR: "Balcones 45", DONANTE_MUN: "Hermosillo", DONANTE_NOMBRE: "Nicole", DONANTE_TELCASA: "", DONANTE_TELMOV: "6621020248", ESTATUS: "Pendiente", IMPORTE: 200, REPARTIDOR_ID: 1)
        
    ]
    
    return lista
}
